name: tinasha_v2
description: "Another MyAnimeList client. Written in Flutter. For fun!"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^14.1.3
  shared_preferences: ^2.2.3
  simple_icons: ^10.1.3
  streaming_shared_preferences: ^2.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  lint: ^2.3.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/images/launcher_icon.png"
  android: true
  web:
    generate: true
    background_color: "#0f172a"
  windows:
    generate: true
    icon_size: 256
